on: [push]

jobs:
  compile_document:
    runs-on: ubuntu-latest
    name: A job to say hello
    container:
      image: ghcr.io/matsavage/dnd-5e-latex-action:latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
