on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile character tex files
        uses: matsavage/latex-action@master
        with:
          working_directory: characters
          compiler: xelatex
          runs: 2
          args: "--file-line-error --interaction=nonstopmode"
