name: Build with xelatex
on:
  push:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile character tex files
        uses: matsavage/dnd-latex-action@master
        with:
          working_directory: .
          root_file: characters/unnamed.tex
          compiler: xelatex
          runs: 2
          args: "--file-line-error --interaction=nonstopmode"
