name: "Test NixOS flake"

on:
  pull_request:
  schedule:
    - cron: "0 13 * * 1"


jobs:
  tests:
    name: Run NixOS Flake and upload generated PDFs
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - name: Set up NixOS
      uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run nix build
      run: nix build

    - name: Show logs on failure
      if: failure()
      run: nix log /nix/store/*dnd-char-sheet*.drv

    - name: Run nix flake check
      run: nix flake check

    - name: Copy output to archive directory
      run: |
       mkdir archive
       cp -r ./result/* ./archive

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: result
        path: archive
